// Deterministic manifest of OG/hero binaries generated by the Python scripts.
// Run manually after regenerating images: bun scripts/build-og-manifest.ts
// Writes public/og/manifest.json. The postbuild guard `check-og-manifest`
// verifies (never regenerates) this manifest.

import { createHash } from "node:crypto";
import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const ROOT = process.cwd();
const MANIFEST_PATH = "public/og/manifest.json";
const MANIFEST_VERSION = 1;
const TEMPLATE_VERSION = "2026-og-v1";
const COMMERCIAL_VALUE = "R$ 99,99";

const SCRIPTS = [
  "scripts/build-city-images.py",
  "scripts/build-city-responsive.py",
  "scripts/build-og-images.py",
];

// Deterministic list of directories/files that belong to the pipeline.
const DIRS = ["public/og", "public/og/cidade", "public/hero/cidade"];
const EXTRA_FILES = ["public/og-image.jpg"];
const OUTPUT_EXTS = new Set([".jpg", ".jpeg", ".webp", ".png"]);
const EXCLUDE_BASENAMES = new Set(["manifest.json"]);

function sha256(buf: Buffer): string {
  return createHash("sha256").update(buf).digest("hex");
}

function readDim(buf: Buffer, ext: string): { w: number; h: number; format: string } | null {
  // PNG
  if (buf[0] === 0x89 && buf[1] === 0x50 && buf[2] === 0x4e && buf[3] === 0x47) {
    return { w: buf.readUInt32BE(16), h: buf.readUInt32BE(20), format: "png" };
  }
  // JPEG
  if (buf[0] === 0xff && buf[1] === 0xd8) {
    let i = 2;
    while (i < buf.length) {
      if (buf[i] !== 0xff) return null;
      const marker = buf[i + 1];
      const size = buf.readUInt16BE(i + 2);
      const isSOF =
        marker >= 0xc0 && marker <= 0xcf && marker !== 0xc4 && marker !== 0xc8 && marker !== 0xcc;
      if (isSOF) return { w: buf.readUInt16BE(i + 7), h: buf.readUInt16BE(i + 5), format: "jpeg" };
      i += 2 + size;
    }
    return null;
  }
  // WebP (VP8/VP8L/VP8X)
  if (
    buf.slice(0, 4).toString("ascii") === "RIFF" &&
    buf.slice(8, 12).toString("ascii") === "WEBP"
  ) {
    const chunk = buf.slice(12, 16).toString("ascii");
    if (chunk === "VP8 ") {
      const w = buf.readUInt16LE(26) & 0x3fff;
      const h = buf.readUInt16LE(28) & 0x3fff;
      return { w, h, format: "webp" };
    }
    if (chunk === "VP8L") {
      const b0 = buf[21], b1 = buf[22], b2 = buf[23], b3 = buf[24];
      const w = 1 + (((b1 & 0x3f) << 8) | b0);
      const h = 1 + (((b3 & 0x0f) << 10) | (b2 << 2) | ((b1 & 0xc0) >> 6));
      return { w, h, format: "webp" };
    }
    if (chunk === "VP8X") {
      const w = 1 + (buf[24] | (buf[25] << 8) | (buf[26] << 16));
      const h = 1 + (buf[27] | (buf[28] << 8) | (buf[29] << 16));
      return { w, h, format: "webp" };
    }
  }
  return null;
}

function listOutputs(): string[] {
  const out = new Set<string>();
  for (const dir of DIRS) {
    for (const name of readdirSync(join(ROOT, dir))) {
      if (EXCLUDE_BASENAMES.has(name)) continue;
      const full = join(dir, name);
      const st = statSync(join(ROOT, full));
      if (!st.isFile()) continue;
      const ext = "." + name.split(".").pop()!.toLowerCase();
      if (!OUTPUT_EXTS.has(ext)) continue;
      out.add(full);
    }
  }
  for (const f of EXTRA_FILES) out.add(f);
  return [...out].sort();
}

function scriptEntry(path: string) {
  const buf = readFileSync(join(ROOT, path));
  return { path, sha256: sha256(buf) };
}

function outputEntry(path: string) {
  const buf = readFileSync(join(ROOT, path));
  const ext = "." + path.split(".").pop()!.toLowerCase();
  const dim = readDim(buf, ext);
  if (!dim) throw new Error(`Cannot read dimensions: ${path}`);
  return {
    path,
    format: dim.format,
    width: dim.w,
    height: dim.h,
    bytes: buf.length,
    sha256: sha256(buf),
  };
}

const scripts = SCRIPTS.slice().sort().map(scriptEntry);
const outputs = listOutputs().map(outputEntry);

const manifest = {
  manifestVersion: MANIFEST_VERSION,
  templateVersion: TEMPLATE_VERSION,
  commercialValue: COMMERCIAL_VALUE,
  generatedAtUtc: new Date().toISOString().replace(/\.\d{3}Z$/, "Z"),
  generatorScripts: scripts,
  outputs,
};

writeFileSync(join(ROOT, MANIFEST_PATH), JSON.stringify(manifest, null, 2) + "\n");
console.log(
  `✓ Wrote ${relative(ROOT, join(ROOT, MANIFEST_PATH))} — ${scripts.length} scripts, ${outputs.length} outputs`,
);
